title: A-NZ Guidance Documents
description: >
  This site provides a range of guides to support the development of
  an A-NZ compliant Peppol Access Point or Service Metadata Publisher.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
sass:
  style: expanded
# Point to the custom CSS
just_the_docs:
  css:
    - assets/css/custom.css

# Navigation (will show in sidebar/top depending on theme)
nav:
  - title: Home
    url: /
  - title: Guidance Note 1
    url: /GuidanceNote01_WETandLCT
  - title: GN2: Payment means and use of the UNCL4461 code list
    url: /GuidanceNote02_PaymentMeans
