title: A-NZ Guidance Documents
description: >
  This site provides a range of guides to support the development of
  an A-NZ compliant Peppol Access Point or Service Metadata Publisher.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
sass:
  style: expanded
# Point to the custom CSS
just_the_docs:
  css:
    - assets/css/custom.css

# Navigation (will show in sidebar/top depending on theme)

nav:
  - Home: README.md
  - GN1_Including WET and LCT on an Invoice: GuidanceNote01_WETandLCT.md
  - GN2_Payment means and use of the UNCL4461 code list: GuidanceNote02_Payment_Means_Code.md
  - GN3_A-NZ Information Security Guidance for e-Invoicing Service Providers: GuidanceNote03_Information_Security.md
  - GN4_Know_Your_Customer: GuidanceNote04_Know_Your_Customer.md
  - GN8_Peppol Participant, Party, Process and Document Identifiers: GuidanceNote08_UseOfIdentifiers.md
  - GN9_Peppol Directory: GuidanceNote09_PeppolDirectory.md
  - GN10_End User Identification: GuidanceNote10_EndUserIdent.md

