title: Home
description: >
  This site provides a range of guides to support the development of
  an A-NZ compliant Peppol Access Point or Service Metadata Publisher.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Point to the custom CSS
just_the_docs:
  aux_links: # optional, for top right menu
    "GitHub Repository":
      - "https://github.com/A-NZ-PEPPOL/Guidance-documents"
  css:
    - assets/css/custom.scss

# Navigation (will show in sidebar/top depending on theme)
nav:
  - title: Home
    url: /README
  - title: Guidance Note 1
    url: /GuidanceNote01_WETandLCT
  - title: Guidance Note 2
    url: /GuidanceNote02_PaymentMeans
