title: A-NZ Guidance Documents
description: >
  This site provides a range of guides to support the development of
  an A-NZ compliant Peppol Access Point or Service Metadata Publisher.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
sass:
  style: expanded
# Point to the custom CSS
just_the_docs:
  css:
    - assets/css/custom.css

# Navigation (will show in sidebar/top depending on theme)

nav:
  - Home: README.md
  - GN1_Including WET and LCT on an Invoice: GuidanceNote01_WETandLCT.md
  - GN2_Payment means and use of the UNCL4461 code list: GuidanceNote02_Payment_Means_Code.md
  - GN3_A-NZ Information Security Guidance for e-Invoicing Service Providers: GuidanceNote03_Information_Security.md
  - GN4_Know_Your_Customer: GuidanceNote04_Know_Your_Customer.md
  - GN8_Peppol Participant, Party, Process and Document Identifiers: GuidanceNote08_UseOfIdentifiers.md
  - GN9_Peppol Directory: GuidanceNote09_PeppolDirectory.md
  - GN10_End User Identification: GuidanceNote10_EndUserIdent.md

nav:
  - title: Home
    url: /
  - title: GN1_Including WET and LCT on an Invoice
    url: /GuidanceNote01_WETandLCT
  - title: GN2_Payment means and use of the UNCL4461 code list
    url: /GuidanceNote02_Payment_Means_Code
  - title: GN3_A-NZ Information Security Guidance for e-Invoicing Service Providers
    url: /GuidanceNote03_Information_Security
  - title: GN4_Know_Your_Customer
    url: /GuidanceNote04_Know_Your_Customer
  - title: GN8_Peppol Participant, Party, Process and Document Identifiers
    url: /GuidanceNote08_UseOfIdentifiers
  - title: GN9_Peppol Directory
    url: /GuidanceNote09_PeppolDirectory
  - title: GN10_End User Identification
    url: /GuidanceNote10_EndUserIdent
